### ISSUE TITLE
Kimai 1 or 2?

### ISSUE THREAD

**Issue by kevinpapst** [felixhummel/kimai-in-docker#2]
Hi @felixhummel !

not tested yet ;-) but already: thanks, nice work 👍 

In your scripts like Makefile, docker-compose.yml and fpm/entrypoint.sh you have code for Kimai 1, but most of the stuff actually looks like Kimai 2 - see also https://github.com/kevinpapst/kimai2/issues/284#issuecomment-431491453

Is this still work-in-progress?

**Comment by felixhummel** [comment]
Hi @kevinpapst !

This is for Kimai 1 in master. While working on it, I stumbled upon the v2 announcement, so I gave it a try. Kimai 2 related stuff is in the [kimai2 branch](https://github.com/felixhummel/kimai-in-docker/tree/kimai2).

**Comment by kevinpapst** [comment]
Ah I see ... I followed your comment which contained the kimai2 branch and then switched between this branch and the master without noticing. Thats explains the mixture ;-)
Cool, I'll try to test it soon. Thats for the contribution!

I would add a chapter in the Kimai2 installation docu about docker containers and then one subheading for your repository. Would you be willing to add a PR with a short explanation for this file: https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md ?
